logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.data.redis: DEBUG
resilience4j.circuitbreaker:
  instances:
    consumerBackend:
      registerHealthIndicator: true
      slidingWindowSize: 5 
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 2
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 2
      eventConsumerBufferSize: 2
spring:
  data:
    redis:
      database: 12
      host: localhost
      port: 6379
      #password: your_redis_password # 如果设置了密码
